---
exclude: ^bazel-
repos:
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.7
  hooks:
  - id: actionlint
- repo: https://github.com/warchant/pre-commit-buildifier
  rev: 0.1.2
  hooks:
  - id: buildifier
    args: [--version=v7.3.1, --lint=warn, --warnings=all, -v]
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v19.1.7
  hooks:
  - id: clang-format
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.9
  hooks:
  - id: ruff
    args: [--fix, --unsafe-fixes]
  - id: ruff-format
- repo: https://github.com/lyz-code/yamlfix
  rev: 1.17.0
  hooks:
  - id: yamlfix
- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.10.0
  hooks:
  - id: shellcheck
- repo: https://github.com/scop/pre-commit-shfmt
  rev: v3.10.0-1
  hooks:
  - id: shfmt-docker
- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    args: [--write-changes]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.43.0
  hooks:
  - id: markdownlint
    args: [--fix]
- repo: https://github.com/renovatebot/pre-commit-hooks
  rev: 39.133.3
  hooks:
  - id: renovate-config-validator
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.14.1
  hooks:
  - id: mypy
    additional_dependencies: [click, pytest]
