filegroup(
    name = "dir",
    srcs = [
        "binsh",
        "file_in_dir.txt",
        "local_file",
        "subdir",
        "symlink_to_file_in_dir",
    ],
    visibility = ["//tests:__subpackages__"],
)
