filegroup(
    name = "dir",
    srcs = [
        "link_to_bin_sh",
        "link_to_file_in_dir2",
        "link_to_link_to_file_in_dir2",
        "local_file",
        "subdir",
    ],
    visibility = ["//tests:__subpackages__"],
)
